name: masterstudy_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.1.0+49

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #networking
  http: ^0.13.4
  rxdart: ^0.27.3
  dio: ">=4.0.4 <6.0.0"
  get_it: ^7.2.0

  #di
  inject:
    path: ./inject.dart/package/inject

  #utils
  meta: ^1.1.6
  equatable: ^1.0.0
  json_annotation: ^4.4.0
  share: 0.6.3+6
  package_info: ^0.4.1
  device_info_plus: ^3.2.2
  overlay_support: ^1.2.1
  image_downloader: ^0.31.0
  intl: ^0.17.0
  flutter_inappwebview: ^5.4.3+7

  #architecture
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1

  #storage latest version on 9march 2022year
  shared_preferences: ^2.0.15
  path_provider: ^2.0.11
  webview_flutter: ^2.0.4
  connectivity_plus: ^2.2.0
  external_path: ^1.0.1

  #analytics
  firebase_crashlytics: ^2.2.0
  firebase_core: ^1.21.0
  firebase_messaging: ^13.0.4

  #ui
  cupertino_icons: ^1.0.3
  google_fonts: ^2.3.1
  flutter_rating_bar: 3.0.1+1
  flutter_svg: ^0.23.0
  shimmer: 1.1.0
  image_picker: ^0.8.4+11
  transparent_image: 1.0.0
  flutter_staggered_grid_view: ^0.6.1
  flutter_html: ^2.2.1
  file_picker: ^4.5.1
  video_player: ^2.3.0
  chewie: ^1.0.0
  font_awesome_flutter: ^10.1.0
  youtube_player_flutter: ^8.0.0
  vimeo_player_flutter: ^0.0.3+1
  url_launcher: ^6.0.20
  cached_network_image: ^3.2.0
  html_unescape: 1.0.1+3
  page_transition: ^1.1.5
  in_app_purchase: ^3.0.8
  image: ^3.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7

  json_serializable: ^6.1.4

  inject_generator:
    path: ./inject.dart/package/inject_generator

flutter:


  uses-material-design: true
  assets:
    - assets/icons/
    - assets/localization/
